### ISSUE TITLE
tplot.py: Could not convert object to NumPy datetime

### ISSUE THREAD

**Issue by pinecypressfxd** [spedas/pyspedas_examples#14]
Hey, Supervised,

I recently migrated my code to ubuntu 20.04.1(from windows 10 system to linux system), when I run the code, get the error:

"/home/dell/.local/lib/python3.8/site-packages/pytplot/MPLPlotter/tplot.py", line 193, in tplot     x_range = np.array(x_range, dtype='datetime64[s]')  ValueError: Could not convert object to NumPy datetime

I located an error appearing in using "/home/dell/.local/lib/python3.8/site-packages/pytplot/tplot.py"

I am trying to solve this problem, if there is a result, I will timely feedback.

**Comment by ericthewizard** [comment]
Thanks for the bug report! This is likely a regression introduced while converting the internal date/time container to numpy datetime objects

**Comment by ericthewizard** [comment]
I think I was able to reproduce/fix the bug; try updating to the latest pyspedas with:

pip install pyspedas --upgrade

The fix should be in pyspedas 1.4.1 / pytplot-mpl-temp 2.1.3.

Thanks again for letting us know about this!
